name: Build for SPES

on:
  workflow_dispatch:
    inputs:
      input_url:
        description: 'URL of the file to build'
        required: true
      

jobs:

  Let_him_cook_broooo:
    runs-on: ubuntu-latest

    steps:
    

    - name: Clean Junks
      run: |
        docker rmi `docker images -q` || true
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/sudo apt/sources.list.d || true
        sudo apt -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* || true
        sudo apt -y autoremove --purge || true
        sudo apt -y autoclean || true
        sudo apt clean || true

    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        swap-size-mb: 8192
        root-reserve-mb: 4096
        temp-reserve-mb: 4096
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'

    - name: Checkout code
      uses: actions/checkout@main
      run:
        git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/ndtai1527/spes_autobuild.git /home/runner/WORKSPACE

    - name: Set up Time 
      run: |
        echo "Setting Vienam timezone"
        sudo timedatectl set-timezone Asia/Ho_Chi_Minh

    - name: Install Stuff
      run: |
        sudo apt-get install -y aria2 rclone sshpass python3 dialog libgtk-3-dev aapt busybox zip unzip p7zip-full openjdk-8-jre zipalign zstd bc android-sdk-libsparse-utils xmlstarlet python3
        sudo pip3 install ConfigObj
    - name: Cooking
      run: |
        chmod 777 /home/runner/WORKSPACE/run.sh && sudo bash /home/runner/WORKSPACE/run.sh /home/runner/WORKSPACE/${{ github.event.inputs.input.url }}
      
